//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATestClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlE5WVpaUnA1UVRpMGVPMmNoV19aYmh1QlBpWSJ9.eyJFbnJvbGxtZW50TnVtYmVyIjoiMTAwIiwiSWQiOiIxY2Q4Mzg5YS01Mzc4LTQzZGQtYjUxOC0xNDM3MDkwYjA4MmEiLCJSZXBvcnRWaWV3IjoiU3lzdGVtIiwiUGFydG5lcklkIjoiIiwiRGVwYXJ0bWVudElkIjoiIiwiQWNjb3VudElkIjoiIiwiaXNzIjoiZWEubWljcm9zb2Z0YXp1cmUuY29tIiwiYXVkIjoiY2xpZW50LmVhLm1pY3Jvc29mdGF6dXJlLmNvbSIsImV4cCI6MTQ5MTk1MTE2MywibmJmIjoxNDc2MjI2MzYzfQ.EjDkRGFhWt9BVL0Vpl8OG2t2aJ6V-J78s8FdWkju2eq-YGf6QNINS_1jXQHkEV7O5uhcnzGXfHziiXPPPF2gdSooCwN8TjXmtQBJWMVX2wD6nnL6kQ0J7mx7k-A2DHd1Ds9AePS7174GYIIqC-uP94h2c_a96mwGdfganlXQHDTA0MCB2KHF0ZgLnoNB-enAbX6VnJAuOLLQSatm4M0VPdbifvqquNggkQb9g1BoGwfPjzpSjo7bdsC1a3b-4ajXzQnFFXdlArhorTrypImJle4nnR7yraO4PV-eyDMibpTSLDc6RvcjR7IjNyEun-YXCtyJawrEeFmluS-pkHqI0w")]
        public string AccessKey {
            get {
                return ((string)(this["AccessKey"]));
            }
            set {
                this["AccessKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string EnrollmentNumber {
            get {
                return ((string)(this["EnrollmentNumber"]));
            }
            set {
                this["EnrollmentNumber"] = value;
            }
        }
    }
}
