//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATestClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string EnrollmentNumber {
            get {
                return ((string)(this["EnrollmentNumber"]));
            }
            set {
                this["EnrollmentNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubscriptionId {
            get {
                return ((string)(this["SubscriptionId"]));
            }
            set {
                this["SubscriptionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AADTenantId {
            get {
                return ((string)(this["AADTenantId"]));
            }
            set {
                this["AADTenantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AADClientId {
            get {
                return ((string)(this["AADClientId"]));
            }
            set {
                this["AADClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AADClientSecret {
            get {
                return ((string)(this["AADClientSecret"]));
            }
            set {
                this["AADClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://azure.microsoft.com/en-us/support/legal/offer-details/")]
        public string AzureOfferDetailsUrl {
            get {
                return ((string)(this["AzureOfferDetailsUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessKeyBilling {
            get {
                return ((string)(this["AccessKeyBilling"]));
            }
            set {
                this["AccessKeyBilling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USD")]
        public string DefaultCurrency {
            get {
                return ((string)(this["DefaultCurrency"]));
            }
            set {
                this["DefaultCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string DefaultLocale {
            get {
                return ((string)(this["DefaultLocale"]));
            }
            set {
                this["DefaultLocale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("US")]
        public string DefaultRegion {
            get {
                return ((string)(this["DefaultRegion"]));
            }
            set {
                this["DefaultRegion"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsageReportListAPIUrl {
            get {
                return ((string)(this["UsageReportListAPIUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-06-01-preview")]
        public string AzureBillingVersion {
            get {
                return ((string)(this["AzureBillingVersion"]));
            }
            set {
                this["AzureBillingVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlE5WVpaUnA1UVRpMGVPMmNoV19aYmh1QlBpWSJ9.eyJFbnJvbGxtZW50TnVtYmVyIjoiMTAwIiwiSWQiOiJiNWU2OWI2Mi0wOWM2LTRmMjktODdmYi0yMTNmMjVkOGExNTMiLCJSZXBvcnRWaWV3IjoiU3lzdGVtIiwiUGFydG5lcklkIjoiIiwiRGVwYXJ0bWVudElkIjoiIiwiQWNjb3VudElkIjoiIiwiaXNzIjoiZWEubWljcm9zb2Z0YXp1cmUuY29tIiwiYXVkIjoiY2xpZW50LmVhLm1pY3Jvc29mdGF6dXJlLmNvbSIsImV4cCI6MTUwNzgyOTI0OCwibmJmIjoxNDkyMDE4MDQ4fQ.Nng57KGNINNTuf8lZB0u4FjM16tu-mrrzWtNQ6vG4_jIJ_Ad06O0U8ROIdM88rvQMyuUlKU3RE-titGq7QoV0ieioKXFrOJ4HTjeUmYET2loriz8UXozk_e2QTmi_FOn-sDgwMhGMRhg0w85cw1p7m2o_2dBizcEhrus8SNb-Z6Ab4A08g9_V2IS1oNJRnU4lGP91sK2CTpWGJUocsTucqTfrUknWPD1ghDSAqkWfGcTvPFQlg7RwXQpG79PfBf0R4ptETBDBfWO7iFNnhphWrKLSCCQ53oLaffvUmlM5YVqeMUH3W63uNMVMIvi9GMA2NFbZcBH3azooSVZpSNDHw")]
        public string AccessKeyUsage {
            get {
                return ((string)(this["AccessKeyUsage"]));
            }
            set {
                this["AccessKeyUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlE5WVpaUnA1UVRpMGVPMmNoV19aYmh1QlBpWSJ9.eyJFbnJvbGxtZW50TnVtYmVyIjoiMTAwIiwiSWQiOiJiNWU2OWI2Mi0wOWM2LTRmMjktODdmYi0yMTNmMjVkOGExNTMiLCJSZXBvcnRWaWV3IjoiU3lzdGVtIiwiUGFydG5lcklkIjoiIiwiRGVwYXJ0bWVudElkIjoiIiwiQWNjb3VudElkIjoiIiwiaXNzIjoiZWEubWljcm9zb2Z0YXp1cmUuY29tIiwiYXVkIjoiY2xpZW50LmVhLm1pY3Jvc29mdGF6dXJlLmNvbSIsImV4cCI6MTUwNzgyOTI0OCwibmJmIjoxNDkyMDE4MDQ4fQ.Nng57KGNINNTuf8lZB0u4FjM16tu-mrrzWtNQ6vG4_jIJ_Ad06O0U8ROIdM88rvQMyuUlKU3RE-titGq7QoV0ieioKXFrOJ4HTjeUmYET2loriz8UXozk_e2QTmi_FOn-sDgwMhGMRhg0w85cw1p7m2o_2dBizcEhrus8SNb-Z6Ab4A08g9_V2IS1oNJRnU4lGP91sK2CTpWGJUocsTucqTfrUknWPD1ghDSAqkWfGcTvPFQlg7RwXQpG79PfBf0R4ptETBDBfWO7iFNnhphWrKLSCCQ53oLaffvUmlM5YVqeMUH3W63uNMVMIvi9GMA2NFbZcBH3azooSVZpSNDHw")]
        public string AccessKeyPricing {
            get {
                return ((string)(this["AccessKeyPricing"]));
            }
            set {
                this["AccessKeyPricing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://automaticbillingspec.blob.core.windows.net/spec/TestEnrollmentUsageApiKey" +
            ".txt")]
        public string TestEnrollmentKeyUrl {
            get {
                return ((string)(this["TestEnrollmentKeyUrl"]));
            }
            set {
                this["TestEnrollmentKeyUrl"] = value;
            }
        }
    }
}
